POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Karl",
    "number": "0655465475"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Karl",
    "number": "654646464"
}